# Generated by Django 6.0.5 on 2026-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='application',
            name='statement',
        ),
        migrations.AddField(
            model_name='application',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='accommodation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/appointment_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='earlier_course_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='earlier_course_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='earlier_course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='earlier_course_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='generated_application_pdf',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/generated_pdfs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/id_proofs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='nature_of_appointment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='official_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='official_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/other_documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='application_uploads/photographs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='present_designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='relieving_order',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/relieving_orders/'),
        ),
        migrations.AddField(
            model_name='application',
            name='scale_of_pay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='application_uploads/signatures/'),
        ),
        migrations.AddField(
            model_name='application',
            name='subject_specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='signed_form',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/signed_forms/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('PDF Generated', 'PDF Generated'), ('Waiting for Signed Form', 'Waiting for Signed Form'), ('Signed Form Uploaded', 'Signed Form Uploaded'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=50),
        ),
    ]
