# Generated by Django 6.0.5 on 2026-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_application_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
