# Generated by Django 6.0.5 on 2026-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='GEN', max_length=20),
            preserve_default=False,
        ),
    ]
