# Generated by Django 6.0.5 on 2026-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(default='Offline', max_length=20),
            preserve_default=False,
        ),
    ]
