# Generated by Django 6.0.5 on 2026-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='eligibility',
        ),
        migrations.AlterField(
            model_name='course',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
