# Generated by Django 6.0.5 on 2026-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_course_description_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats',
        ),
        migrations.AddField(
            model_name='course',
            name='seat_status',
            field=models.CharField(default='Vacant', max_length=20),
        ),
    ]
