# Generated by Django 6.0.5 on 2026-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_course_is_closed_remove_course_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_schedules/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
