# Generated by Django 6.0.5 on 2026-06-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_courseschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='earlier_course_attended',
        ),
        migrations.RemoveField(
            model_name='application',
            name='earlier_course_duration',
        ),
        migrations.RemoveField(
            model_name='application',
            name='earlier_course_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='earlier_course_place',
        ),
        migrations.AlterField(
            model_name='application',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='application',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='mailing_address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='official_address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='subject_specialization',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='EarlierAttendedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('completion_month_year', models.CharField(blank=True, max_length=20)),
                ('center_name', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earlier_courses', to='core.application')),
            ],
        ),
    ]
