# Generated by Django 6.0.5 on 2026-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_application_earlier_course_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
