# Generated by Django 6.0.5 on 2026-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_application_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='generated_application_docx',
            field=models.FileField(blank=True, null=True, upload_to='application_uploads/generated_docs/'),
        ),
    ]
