# Generated by Django 6.0.5 on 2026-06-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_certificate_qr_code_alter_application_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appointment_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='application',
            name='relieving_order',
        ),
        migrations.RemoveField(
            model_name='application',
            name='signature',
        ),
    ]
